package com.didww.sdk.resource;

import com.github.jasminb.jsonapi.annotations.Meta;

import java.util.Map;

/**
 * Base class for resources carrying a server-provided JSON:API {@code meta} object.
 *
 * <p>{@code getMeta} is declared here rather than generated by Lombok so its JVM descriptor stays
 * {@code ()Ljava/util/Map;} — what consumers compiled against before {@link MetaMap} existed.
 */
public abstract class MetaResource extends BaseResource {

    @Meta
    protected MetaMap meta;

    public Map<String, String> getMeta() {
        return meta;
    }
}
